Dotfiles update

diff --git a/k8s/k9s/plugins.yaml b/k8s/k9s/plugins.yaml
--- a/k8s/k9s/plugins.yaml
+++ b/k8s/k9s/plugins.yaml
@@ -22,7 +22,7 @@ plugins:
     args:
       - -c
       - |
-        oc show secret -n $NAMESPACE $NAME | bat --style=numbers --color=always --line-range :500 --paging=always -l json;
+        oc show secret -n $NAMESPACE $NAME | bat --style=numbers --color=always --line-range :500 --paging=never -l json --style=numbers,header ;
         #read -n 1 -s -r -p "Press any key to continue";
   ## ########################################
   ## Cloudrock Cluster
@@ -64,7 +64,7 @@ plugins:
           kube_version:$r.spec.kube_version,infrastructure:$r.spec.infrastructure,location:$r.spec.location,multiaz:$r.spec.multiaz,
           workerPoolStatus:$r.status.workerPoolStatus,clusterStatus:$r.status.clusterStatus,clusterVersionStatus:$r.status.clusterVersionStatus,
           AddonStatus: (.)} ' \
-          | yq -P | bat --style=numbers --color=always --line-range :500 -l yaml --paging=always;
+          | yq -P | bat --color=always --line-range :500 -l yaml --paging=always --style=numbers,header ;
         echo "oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o json | jq '. as \$r |$r.status.addonStatus | {CRC: (\$r.metadata.name ), NS:( \$r.metadata.namespace ), workerPoolStatus:\$r.status.workerPoolStatus,clusterStatus:\$r.status.clusterStatus,clusterVersionStatus:\$r.status.clusterVersionStatus, AddonStatus: (.)} ' | yq -P";
         #read -n 1 -s -r -p "Press any key to continue";
     # Whether
@@ -84,6 +84,8 @@ plugins:
     args:
       - -c
       - |
+        DEBUG=$( fzf --header 'DEBUG' --height 30% < <( echo "" ; echo "true"; ) );
+        [ -n "${DEBUG}" ] && { export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] ' ; set -x; };
         #oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o jsonpath={.spec.addon} | yq  '.|keys|.[]' | fzf -m --header '$NAME' --height 30% --query='' --preview-window=right,70% --preview 'oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o jsonpath={.spec.addon.{}} | yq -P' ;
         #oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o jsonpath={.spec.addon} | jq -r '.|keys|.[]' | fzf --header '$NAME addons status' --height 30% --query='' --preview-window=right,70% --preview 'oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o json | yq -P '\''. as $r | {"{}":( $r.spec.addon.{} ), "Status":($r.status.addonStatus.{}) }'\'' ' ;
         oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o json | jq -r '. as $r | ( $r.spec.addon | keys[] as $key | "\($key) |\($r.status.addonStatus[$key].status)" )' | fzf --header '$NAME addons status (Press CTRL-R to reload)' --height 30% --query='' --preview-window=right,70% --preview 'ADDON=$( awk '\''{print $1}'\'' <<<{} ) ; oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o json | yq -P '\''. as $r | {"'\''$ADDON'\''":( $r.spec.addon.'\''$ADDON'\'' ), "Status":($r.status.addonStatus.'\''$ADDON'\'') }'\'' ' --bind 'ctrl-r:reload( oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o json | jq -r '\''. as $r | ( $r.spec.addon | keys[] as $key | "\($key) |\($r.status.addonStatus[$key].status)" )'\'' )' || echo "" ;
@@ -107,6 +109,8 @@ plugins:
     args:
       - -c
       - |
+        DEBUG=$( fzf --header 'DEBUG' --height 30% < <( echo "" ; echo "true"; ) );
+        [ -n "${DEBUG}" ] && { export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] ' ; set -x; };
         ##
         _ADDON=$( oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o jsonpath={.spec.addon} | jq -r '.|keys|.[]' | fzf --header '$NAME addon reconcile' --height 30% --query='' --preview-window=right,70% \
             --preview 'oc --context $CONTEXT get crc $NAME -n $NAMESPACE -o json | yq -P '\''. as $r | {"{}":( $r.spec.addon.{} ), "Status":($r.status.addonStatus.{}) }'\'' ' ; )
@@ -150,7 +154,7 @@ plugins:
     args:
       - -ec
       - |
-        #DEBUG=1
+        DEBUG=$( fzf --header 'DEBUG' --height 30% < <( echo "" ; echo "true"; ) )
         [ -n "${DEBUG}" ] && { export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] ' ; set -x; };
 
         _HELPERS=~/bin/_k9s-helpers.sh
@@ -191,7 +195,7 @@ plugins:
         test -z "$_CLUSTER" && _CLUSTER=$NAME ;
         #test "$_CLUSTER" == "$NAME" && { _CLUSTER=$NAME ; ocm list clusters -p search="name='$NAME'" --columns ID --no-headers || _rosa-token-refresh ; };
         #test "$_CLUSTER" != "$NAME" &&
-        ocm list clusters -p search="name='$_CLUSTER'" --columns ID --no-headers || _rosa-token-refresh ;
+        ocm list clusters -p search="name='$_CLUSTER'" --columns ID --no-headers || ( echo _rosa-token-refresh ; _rosa-token-refresh );
         #read -n 1 -s -r -p "Press any key to continue";
 
         _CLUSTER=( $( fzf --header 'Open CLUSTER Concole' --height 30% --preview-window=right,70% --preview 'oc show secret {} -n $NAMESPACE --context $CONTEXT ' < <( echo $_CLUSTER ;
@@ -231,6 +235,8 @@ plugins:
     args:
       - -c
       - |
+        DEBUG=$( fzf --header 'DEBUG' --height 30% < <( echo "" ; echo "true"; ) );
+        [ -n "${DEBUG}" ] && { export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] ' ; set -x; };
         ## nl
         #oc --context $CONTEXT -n cloudrock-controller logs -f deployment/cloudrock-controller | grep -iE '$NAME' --color=always | nl -ba
         ## tac | bat --line-range :10 | tac | bat
@@ -267,6 +273,9 @@ plugins:
     description: "Controller Addon Logs"
     scopes:
       - cloudrockclusters
+      - cloudrockconnectivities
+      - cloudrockvpcs
+      - cloudrocks
       - deployments
       - deployments.v1.apps
     # The command to execute. We use the standard kubectl get command for our CRD.
@@ -274,8 +283,10 @@ plugins:
     args:
       - -c
       - |
+        DEBUG=$( fzf --header 'DEBUG' --height 30% < <( echo "" ; echo "true"; ) );
+        [ -n "${DEBUG}" ] && { export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] ' ; set -x; };
         ##
-        _LOGGER=$( fzf --header 'Use Gonzo ?' --height 30% < <( echo "" ; echo "gonzo --format=json" ; echo "gonzo --format=text" ; ) --preview 'echo {}' || echo "" )
+        _LOGGER=$( fzf --header 'Use Gonzo ?' --height 30% < <( echo "" ; echo "filter $NAME" ; echo "gonzo --format=json" ; echo "gonzo --format=text" ; ) --preview 'echo {}' || echo "" )
         _SINCE=$( fzf --header 'SINCE_TIME' --height 30% < <( echo "" ; echo 10m ; echo 1h ; echo 6h ; echo 12h ; echo 24h ; echo 360h ; ) --preview 'echo {}' || echo "" )
         case $_LOGGER in
           gonzo*)
@@ -285,9 +296,16 @@ plugins:
               _CMD="oc --context $CONTEXT -n cloudrock-controller logs -f $_RES ${_SINCE:+--since=$_SINCE} "
               eval "$_CMD | $_LOGGER " ;
           ;;
+          filter*)
+            _POD=$( oc --context $CONTEXT -n cloudrock-controller get pod -o name | fzf -m --header '$NAME' --height 30% --query='' --preview-window=right,70% )
+            test -n "$_POD" || { echo "No POD selected" ; read -n 1 -s -r -p "Press any key to continue"; exit 0 ; }
+            _CMD="oc --context $CONTEXT -n cloudrock-controller logs -f $_POD ${_SINCE:+--since=$_SINCE}"
+            echo $_CMD;
+            oc --context $CONTEXT -n cloudrock-controller logs -f $_POD ${_SINCE:+--since=$_SINCE} | grep $NAME | bat --paging=never -l json --style=numbers,header ;
+            ;;
           *)
             _POD=$( oc --context $CONTEXT -n cloudrock-controller get pod -o name | fzf -m --header '$NAME' --height 30% --query='' --preview-window=right,70% )
-            test -n "$_POD" || { echo "No POD selected" ; exit 0 ; }
+            test -n "$_POD" || { echo "No POD selected" ; read -n 1 -s -r -p "Press any key to continue"; exit 0 ; }
             _CMD="oc --context $CONTEXT -n cloudrock-controller logs -f $_POD ${_SINCE:+--since=$_SINCE}"
             echo $_CMD;
             oc --context $CONTEXT -n cloudrock-controller logs -f $_POD ${_SINCE:+--since=$_SINCE} | bat --paging=never -l json --style=numbers,header ;
@@ -303,19 +321,20 @@ plugins:
 
   ## ########################################
   ## MARK: Cloudrock Controller
-  ## MARK: Token Rotate
+  ## MARK: Token Rotate Token
   ## ########################################
   cp-token-rotate:
     shortCut: Shift-R
     description: "CP Token Rotate"
     scopes:
       - cloudrockclusters
+      - deployments.v1.apps
     # The command to execute. We use the standard kubectl get command for our CRD.
     command: /usr/local/bin/bash
     args:
       - -ec
       - |
-        #DEBUG=1
+        DEBUG=$( fzf --header 'DEBUG' --height 30% < <( echo "" ; echo "true"; ) );
         [ -n "${DEBUG}" ] && { export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] ' ; set -x; };
 
         _HELPERS=~/bin/_k9s-helpers.sh
@@ -326,12 +345,16 @@ plugins:
             read -n 1 -s -r -p "Press any key to continue (Ctrl-C to abort)" ;
         done
 
+        NAMESPACE1="${NAMESPACE//cloudrock-controller/ap}"
+        echo "$NAMESPACE1"
         echo "${NAMESPACE}"
         _CLUSTER=$( echo "${NAMESPACE}" | awk -F'-' '{for(i=2;i<=(NF-4);i++){if(i>2)printf "-";printf $i}}' )
 
         ocm list clusters -p search="name='$_CLUSTER'" --columns ID --no-headers || _rosa-token-refresh ;
 
-        _CLUSTER=( $( fzf -m --header $'CLUSTER List\nhttps://rb.gy/4c5s2r\nhttps://pages.github.ibm.com/ibm-saas-platform/MultiCloud-SaaS-Framework/Architectural_Overview/Resources/mcsp_clusters/#__tabbed_2_1' --height 30% --preview-window=right,70% --preview 'oc show secret {} -n $NAMESPACE --context $CONTEXT ' < <( echo $_CLUSTER ;
+        _CLUSTER=( $( fzf -m --header $'CLUSTER List\nhttps://rb.gy/4c5s2r\nhttps://pages.github.ibm.com/ibm-saas-platform/MultiCloud-SaaS-Framework/Architectural_Overview/Resources/mcsp_clusters/#__tabbed_2_1' \
+                --height 30% --preview-window=right,70% \
+                --preview 'echo oc show secret {} -n ap --context $CONTEXT ' < <( echo $_CLUSTER ;
                     xargs -n1 <<< "ap-usge1-pp-dp ap-usge1-pp-cp ap-usge1-dp-01 ap-usge1-cp-01 ap-dp-t-fedramp ap-cp-t-fedramp";
                     xargs -n1 <<< "ap-cp-001 ap-dp-001 ap-cp-101 ap-dp-101";
                     xargs -n1 <<< "ap-use1-d-cp-01 ap-use1-d-dp-01 ap-use1-t-cp-01 ap-use1-t-dp-01 ap-use1-cp-01 ap-use1-dp-01";
@@ -341,6 +364,7 @@ plugins:
         _CLUSTERS=${_CLUSTER[@]} ; echo "Selected Clusters: $_CLUSTERS"
 
         _CMD="oc govcloud token-patch -c ${_CLUSTERS// /,} --restart"
+        echo $_CMD
         echo -e "Run cmd below (Ctrl-C to abort) ?\n";
         read -n 1 -s -r -p "$_CMD"; echo;
         eval "$_CMD" || true ; echo "Done.";
@@ -380,8 +404,69 @@ plugins:
     view:
       name: oc-routes
 
+  ## ########################################
+  ## MARK: AWS Credentials Validate
+  ## ########################################
+  aws-credentials-validate:
+    shortCut: Shift-V
+    description: "CP / Atlantis AWS Credentials Validate"
+    scopes:
+      - cloudrockclusters
+      - deployments.v1.apps
+      #- secrets.v1
+      #- secrets
+      - secret
+      - pods
+    # The command to execute. We use the standard kubectl get command for our CRD.
+    command: /usr/local/bin/bash
+    args:
+      - -c
+      - |
+        DEBUG=$( fzf --header 'DEBUG' --height 30% < <( echo "" ; echo "true"; ) );
+        [ -n "${DEBUG}" ] && { export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] ' ; set -x; };
 
-  # Defines a plugin to provide a `ctrl-l` shortcut to tail the logs while in pod view.
+        _HELPERS=~/bin/_k9s-helpers.sh
+        while true ; do
+            test -f $_HELPERS || { echo "$_HELPERS not found"; } ;
+            echo "source $_HELPERS" ;
+            source $_HELPERS && break ;
+            read -n 1 -s -r -p "Press any key to continue (Ctrl-C to abort)" ;
+        done
+
+        unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION AWS_CREDS_VALIDATE SECRET1_DATA ;
+
+        NAMESPACE1="${NAMESPACE//cloudrock-controller/ap}"
+        NAMESPACE1=$( oc get ns -o jsonpath={..metadata.name} -A | xargs -n1 | grep atlantis ) ;
+        NAMESPACE2=$( echo $NAMESPACE1 | sed 's/atlantis-//g' ) ;
+        echo "NAMESPACE1 = $NAMESPACE1" | xargs ;
+        echo "NAMESPACE2 = $NAMESPACE2" ;
+        NAMESPACE1=$( echo "$NAMESPACE1 $NAMESPACE2" | xargs -n1 | fzf -m --header 'Select NS (remove filter to see full list)' --height 30% --query="atlantis" --preview-window=right,70% --preview 'oc get secret -n {}' || echo "" ) ;
+        echo NS = $NAMESPACE1
+        test -n "$NAMESPACE1" || { echo "No NAMESPACE selected" ; read -n 1 -s -r -p "Press any key to continue (Ctrl-C to abort)" ; exit 0 ; }
+
+        SECRET1=$( oc get secret -n $NAMESPACE1 -o jsonpath={..metadata.name} | xargs -n1 | fzf -m --header 'Select Secret' --height 30% --query="" --preview-window=right,70% --preview 'oc get secret -n '$NAMESPACE1' {} -o yaml' || echo "" )
+        echo SECRET = $SECRET1
+        test -n "$SECRET1" || { echo "No SECRET selected" ; read -n 1 -s -r -p "Press any key to continue (Ctrl-C to abort)" ; exit 0 ; }
+
+        SECRET1_DATA=$( oc get secret -n $NAMESPACE1 $SECRET1 -o json | yq -oj '{"data": .data |  with_entries(.value |= @base64d)}' | jq -c ) ;
+
+        read -n 1 -s -r -p "Show AWS Credentials (Enter to skip) [y] ? " YN ; echo ;
+        test "$YN" == "y" && { echo $SECRET1_DATA; yq -P <<<$SECRET1_DATA; } || true ;
+
+        grep -q region <<<$SECRET1_DATA || AWS_REGION1=$( export $( jq -r '.data | "AWS_ACCESS_KEY_ID=\(.aws_access_key_id // .awsaccesskeyid ) AWS_SECRET_ACCESS_KEY=\(.aws_secret_access_key // .awssecretaccesskey ) AWS_REGION=us-east-1"' <<<$SECRET1_DATA ) ; aws ec2 describe-regions --query 'Regions[].RegionName' --output text | xargs -n1 | fzf -m --header 'AWS_REGION' --height 30% --preview-window=right,70% --query="'east-1" ) ;
+
+        AWS_CREDS_VALIDATE=$( jq -r '.data | "AWS_ACCESS_KEY_ID=\(.aws_access_key_id // .awsaccesskeyid ) AWS_SECRET_ACCESS_KEY=\(.aws_secret_access_key // .awssecretaccesskey ) AWS_REGION=\(.region // "'$AWS_REGION1'" ) aws sts get-caller-identity"' <<<$SECRET1_DATA ) || true;
+
+        read -n 1 -s -r -p "Run AWS Credentials Vatidation (Ctrl-C to abort) ?"; echo ;
+        echo "$AWS_CREDS_VALIDATE" ;
+        echo "$AWS_CREDS_VALIDATE" | bash || true ;
+        read -n 1 -s -r -p "Press any key to continue (Ctrl-C to abort)" ;
+    view:
+      name: aws-credentials-validate
+
+  ## ########################################
+  ## Defines a plugin to provide a `ctrl-l` shortcut to tail the logs while in pod view.
+  ## ########################################
   fred:
     # Define a mnemonic to invoke the plugin
     shortCut: Ctrl-L
@@ -487,8 +572,36 @@ plugins:
   ## ########################################
   ## ARGOCD
   ## ########################################
+  argocd-login:
+    shortCut: Shift-L
+    confirm: false
+    description: Login ArgoCD and List Projects
+    scopes:
+      - applications
+      - apps
+      - appsets
+    background: false
+    command: bash
+    args:
+      - -c
+      - |
+        NS=$( oc get ns -l for-product,component-name -o custom-columns="NAME_SHOULD_NOT_ATLANTIS:.metadata.name" | grep -vi atlantis | fzf --prompt="Select NS: " --height 30% --preview-window=right,70% --preview ' ' ) ;
+        argocd login $( oc -n argocd-worker get route argocd-server -o jsonpath={.spec.host} ) --skip-test-tls --grpc-web --username=$( oc -n $NS get secret argo -o jsonpath={.data.username} | base64 -d ) --password=$( oc -n $NS get secret argo -o jsonpath={.data.password} | base64 -d ) ;
+        echo
+        argocd proj list --grpc-web
+        echo
+        argocd appset list
+        echo
+        argocd app list -o json | jq -r '.[] | [.metadata.name,.spec.project,.status.sync.status,.status.health.status,"\(.spec.source.repoURL|sub("\\.git"; "") )/-/tree/\(.spec.source.targetRevision)/\(.spec.source.path)"] | @tsv' | column -t -s $'\t'
+        echo
+        echo argocd app list
+        echo
+        echo '## https://medium.com/@ezzatelshazly7/argocd-stuck-in-refreshing-state-troubleshooting-resolution-3ad58f9b9f3b'
+        echo '## https://oneuptime.com/blog/post/2026-02-26-argocd-cluster-credentials/view'
+        read -n 1 -s -r -p "Press any key to continue";
+
   argocd:
-    shortCut: "s"
+    shortCut: ss
     description: Sync ArgoCD Application
     scopes:
       - application
